theme: jekyll-theme-minimal

title: [Bird the Gap]
description: [A capstone project by MLIS candidate Ellen Namakaokealoha Kamoe, created with [eBird](https://ebird.org/about) & the [Cornell Lab of Ornithology](https://www.birds.cornell.edu/home)]

logo: [images/bird-the-gap-logo.png]