theme: jekyll-theme-minimal

title: Bird the Gap
description: A capstone project by Ellen Namakaokealoha Kamoe (MLIS '20). Read the full documentation [here](https://ekamoe.gitbook.io/bird-the-gap-documentation/).
